# Linear Algebra
https://github.com/srush/GPU-Puzzles

## Dot Product

## Vector Norm

## Matrix Vector Product

## Matrix Norm

## Matrix Matrix Product

## Convolution

## FFT

## Multiply Accumulate

## Scalar Vector Product

## Scalar Matrix Product

## Scalar Vector Addition

## Scalar Matrix Addition

In [14]:
import numpy as np
import scipy as sp
import pandas as pd
import sys
from timeit import default_timer as timer
import matplotlib as mpl
import matplotlib.pyplot as plt
import math


INTMAX = 2147483647

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

m1 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2 = np.matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

## Dot Product

In [6]:
print(a1)
print(a2)
dot_result = np.dot(a1, a2)
print(dot_result)

[1 2 3]
[4 5 6]
32


## Matrix Vector Product

In [8]:
print(m2)
print(a1)
mv_prod = np.dot(m2, a1)
print(mv_prod)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[1 2 3]
[[1 2 3]]


## Matrix Matrix Product

In [9]:
print(m1)
print(m2)
mm_prod = np.matmul(m1, m2)
print(mm_prod)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##  Map / Zip / Guard

In [11]:
mzg_result = a1 + 10
print(a1)
print(mzg_result)

[1 2 3]
[11 12 13]


## 2D Map

In [12]:
m2d_result = m1 + 10
print(m1)
print(m2d_result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


## Broadcast

In [15]:
broad_result = a1 + np.transpose(a2)
print(a1)
print(a2)
print(broad_result)

[1 2 3]
[4 5 6]
[5 7 9]


## Pooling

In [23]:
a_test = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
pool_result = np.zeros(a_test.shape)
for i in range(0, len(a_test)):
    pool_result[i] = a_test[max(i - 2, 0) : i + 1].sum()
print(a_test)
print(pool_result)

[1 2 3 4 5 6 7 8 9]
[ 1.  3.  6.  9. 12. 15. 18. 21. 24.]


## 1D Convolution

In [16]:
conv_result = np.convolve(a1, a2)
print(a1)
print(a2)
print(conv_result)

[1 2 3]
[4 5 6]
[ 4 13 28 27 18]


## 2D Conv

In [29]:
conv_kernel = np.matrix([[1, 1], [0, 0]])
conv2d_result = sp.signal.convolve2d(m1, conv_kernel, boundary='symm')
conv2d_result = conv2d_result[0:3, 0:3]
print(conv2d_result)

[[ 2  3  5]
 [ 8  9 11]
 [14 15 17]]


## Axis Sum

In [19]:
print(m1)
print(m1.sum(axis=0))
print(m1.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[12 15 18]]
[[ 6]
 [15]
 [24]]
